apiVersion: v1
kind: ReplicationController
metadata:
  name: mavenwebapprc
  namespace: manu-ts
spec:
  replicas: 1
  selector: 
    app: mavenwebapp
  template:
    metadata:
      name: mavenwebapppod
      labels:
        app: mavenwebapp
    spec:
      containers:
      - name: mavenwebapplication
        image: naresh06092020/maven-web-application:1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mavenwebappsvc
  namespace: manu-ts
spec:
  type: NodePort
  selector:
    app: mavenwebapp
  ports:
  - port: 80
    targetPort: 8080  